spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:sequence
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql