server:
  port: 8080
  shutdown: graceful
collapse:
  executor:
    enabled: true
    collecting-wait-time: -1
    wait-threshold: 10
    thread-pool:
      core-pool-size: 100
      maximum-pool-size: 100
      queue-size: 0
      prefix: collapse-async
    servlet:
      enabled: true
      batch-size: 64
      uris:
        - /test/collapse1
        - /test/collapse100
