server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 200
  undertow:
    threads:
      worker: 200
collapse:
  executor:
    enabled: true
    collecting-wait-time: -1
    wait-threshold: 10
    servlet:
      enabled: true
      batch-size: 64
      collapse-policies:
        test-policy:
          collapse-query-string: true
          collapse-request-headers:
            - auth
            - user-id
      collapse-groups:
        - collapse-policy-name: test-policy
          uris:
            - /test/collapse1
            - /test/collapse100
