server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 400

collapse:
  executor:
    enabled: true
    wait-threshold: 10
    collecting-wait-time: -1

    #[Servlet] collapse request configuration
    servlet:
      enabled: true
      batch-size: 64
      collapse-policies:
        test-policy:
          collapse-request-headers:
            - auth
            - user-id
      collapse-groups:
        - collapse-policy-name: test-policy
          uris:
            - /test/collapse1
            - /test/collapse100

    #[RestTemplate] collapse request configuration
    rest-template:
      enabled: true
      collapse-groups:
        - uris:
            - /user/*
            - /test/noop*

    #[WebClient] collapse request configuration
    web-client:
      enabled: true
      collapse-groups:
        - uris:
            - /user/*
            - /test/noop*