server:
  port: 8080
  shutdown: graceful
  undertow:
    threads:
      worker: 200
collapse:
  executor:
    enabled: true
    collecting-wait-time: -1
    wait-threshold: 10
    servlet:
      enabled: true
      batch-size: 64
      uris:
        - /test/collapse1
        - /test/collapse100
