server:
  port: 8080
  shutdown: graceful

collapse:
  executor:
    enabled: true
    collecting-wait-time: -1
    wait-threshold: 10

    #[Servlet] collapse request configuration
    servlet:
      enabled: true
      batch-size: 64
      collapse-policies:
        test-policy:
          collapse-request-headers:
            - auth
            - user-id
      collapse-groups:
        - collapse-policy-name: test-policy
          uris:
            - /test/collapse1
            - /test/collapse100

    #[WebClient] collapse request configuration
    web-client:
      enabled: true
      collapse-groups:
        - collapse-policy-name: "*"
          uris:
            - /user/*

    #[RestTemplate] collapse request configuration
    rest-template:
      enabled: true
      collapse-groups:
        - collapse-policy-name: "*"
          uris:
            - /user/*